// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/local_db/add_contact_db.dart';
import 'data/local_db/categoty_db.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 6470066468063900777),
      name: 'Categories',
      lastPropertyId: const IdUid(2, 2675768617339291445),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 1116105305432243300),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 2675768617339291445),
            name: 'category',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(2, 7590440867705058817),
      name: 'User',
      lastPropertyId: const IdUid(7, 3396187760126337672),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 4824096626496750813),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 7040326088090854003),
            name: 'firstName',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 5447170340391889587),
            name: 'lastName',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 4917525362327124939),
            name: 'email',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 4206567614152311368),
            name: 'mobileNumber',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 6610956785046597625),
            name: 'category',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 3396187760126337672),
            name: 'image',
            type: 23,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(2, 7590440867705058817),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    Categories: EntityDefinition<Categories>(
        model: _entities[0],
        toOneRelations: (Categories object) => [],
        toManyRelations: (Categories object) => {},
        getId: (Categories object) => object.id,
        setId: (Categories object, int id) {
          object.id = id;
        },
        objectToFB: (Categories object, fb.Builder fbb) {
          final categoryOffset = fbb.writeString(object.category);
          fbb.startTable(3);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, categoryOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Categories(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              category: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''));

          return object;
        }),
    User: EntityDefinition<User>(
        model: _entities[1],
        toOneRelations: (User object) => [],
        toManyRelations: (User object) => {},
        getId: (User object) => object.id,
        setId: (User object, int id) {
          object.id = id;
        },
        objectToFB: (User object, fb.Builder fbb) {
          final firstNameOffset = fbb.writeString(object.firstName);
          final lastNameOffset = fbb.writeString(object.lastName);
          final emailOffset = fbb.writeString(object.email);
          final categoryOffset = fbb.writeString(object.category);
          final imageOffset = fbb.writeListInt8(object.image);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, firstNameOffset);
          fbb.addOffset(2, lastNameOffset);
          fbb.addOffset(3, emailOffset);
          fbb.addInt64(4, object.mobileNumber);
          fbb.addOffset(5, categoryOffset);
          fbb.addOffset(6, imageOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = User(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              mobileNumber:
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
              email: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, ''),
              firstName: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              lastName: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, ''),
              category: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 14, ''),
              image: const fb.Uint8ListReader(lazy: false).vTableGet(
                  buffer, rootOffset, 16, Uint8List(0)) as Uint8List);

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [Categories] entity fields to define ObjectBox queries.
class Categories_ {
  /// see [Categories.id]
  static final id =
      QueryIntegerProperty<Categories>(_entities[0].properties[0]);

  /// see [Categories.category]
  static final category =
      QueryStringProperty<Categories>(_entities[0].properties[1]);
}

/// [User] entity fields to define ObjectBox queries.
class User_ {
  /// see [User.id]
  static final id = QueryIntegerProperty<User>(_entities[1].properties[0]);

  /// see [User.firstName]
  static final firstName =
      QueryStringProperty<User>(_entities[1].properties[1]);

  /// see [User.lastName]
  static final lastName = QueryStringProperty<User>(_entities[1].properties[2]);

  /// see [User.email]
  static final email = QueryStringProperty<User>(_entities[1].properties[3]);

  /// see [User.mobileNumber]
  static final mobileNumber =
      QueryIntegerProperty<User>(_entities[1].properties[4]);

  /// see [User.category]
  static final category = QueryStringProperty<User>(_entities[1].properties[5]);

  /// see [User.image]
  static final image =
      QueryByteVectorProperty<User>(_entities[1].properties[6]);
}
